#define VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}"
#cmakedefine SANE_FOUND
#define PROGRAM_NAME "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}"
#define HOMEPAGE "${CPACK_NSIS_URL_INFO_ABOUT}"
#define TEMP_DIR PROGRAM_NAME

